//
//  Recommendation.swift
//  ARCIntelligence
//
//  Created by ARC Labs Studio on 18/11/2025.
//

import Foundation

/// A single recommendation generated by an AI provider.
public struct Recommendation: Sendable, Identifiable, Codable, Equatable {
    // MARK: - Properties

    /// Unique identifier for the recommendation
    public let id: UUID

    /// Title or name of the recommended item
    public let title: String

    /// Detailed description of the recommendation
    public let description: String

    /// Confidence score (0.0 to 1.0)
    public let confidence: Float

    /// Optional category or type
    public let category: String?

    /// Optional metadata
    public let metadata: [String: String]

    // MARK: - Initialization

    public init(
        id: UUID = UUID(),
        title: String,
        description: String,
        confidence: Float,
        category: String? = nil,
        metadata: [String: String] = [:]
    ) {
        self.id = id
        self.title = title
        self.description = description
        self.confidence = max(0.0, min(1.0, confidence))
        self.category = category
        self.metadata = metadata
    }
}
